name: main.cpp
	g++ main.cpp -I/usr/include/nite -I/usr/include/ni -I/opt/local/include -L/opt/local/lib -o ../Bin/AS3OpenNI-Bridge -lboost_regex -lboost_regex-mt -lboost_system -lXnVNite_1_3_1 -lOpenNI

clean:
	rm -f name