OSTYPE := $(shell uname -s)

SRC_FILES = \
	../AS3OpenNI/main.cpp \
	../AS3OpenNI/kbhit.cpp \
	../AS3OpenNI/signal_catch.cpp \
	../AS3OpenNI/skeleton.cpp \
	../AS3OpenNI/params.cpp \
	../AS3OpenNI/setup_sockets.cpp

INC_DIRS = ../AS3OpenNI

EXE_NAME = AS3OpenNI_Alpha_1.0.5
include ../NiteSampleMakefile